# Generated by Django 5.0.3 on 2024-03-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ticket_attribute', models.CharField(max_length=100)),
                ('prf_attribute', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('open_from', models.DateTimeField()),
                ('open_to', models.DateTimeField()),
                ('ticket_time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('theater', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('fail', models.BooleanField(default=False)),
                ('fail_reason', models.CharField(blank=True, max_length=200)),
                ('search_keyword', models.CharField(max_length=100)),
            ],
        ),
    ]
