# Generated by Django 5.0.3 on 2024-03-17 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicals',
            name='source_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='musicals',
            name='cast',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='musicals',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='musicals',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='musicals',
            name='open_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='musicals',
            name='open_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='musicals',
            name='poster',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='musicals',
            name='prf_attribute',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='musicals',
            name='price',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='musicals',
            name='theater',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='musicals',
            name='ticket_attribute',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
