# Generated by Django 5.0.3 on 2024-03-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical', '0002_musicals_source_id_alter_musicals_cast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicals',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
