# Generated by Django 5.0.3 on 2024-03-24 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical', '0003_musicals_is_live'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='musicals',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musical.categories'),
        ),
        migrations.AlterField(
            model_name='musicals',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musical.locations'),
        ),
    ]
