# Generated by Django 5.0.3 on 2024-04-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical', '0005_genres_musicals_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=100)),
                ('sequence', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], unique=True)),
            ],
        ),
    ]
