# Generated by Django 5.0.3 on 2024-06-16 10:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical', '0009_rename_category_name_categories_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=50)),
                ('source_link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('push_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=100)),
                ('user_nickname', models.CharField(max_length=50)),
                ('user_last_login', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='musicals',
            name='ticket_time',
        ),
        migrations.CreateModel(
            name='MusicalSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=50)),
                ('series_description', models.TextField()),
                ('ticket_time', models.DateTimeField()),
                ('cast', models.CharField(blank=True, max_length=200)),
                ('reservation_source', models.CharField(blank=True, max_length=100)),
                ('musical_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musical.musicals')),
            ],
        ),
        migrations.CreateModel(
            name='MusicalReservationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_link', models.CharField(max_length=100)),
                ('series_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musical.musicalseries')),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musical.musicalsource')),
            ],
        ),
        migrations.CreateModel(
            name='TicketNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('musical_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musical.musicals')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musical.users')),
            ],
        ),
    ]
